### ISSUE TITLE
S3に直で上げたい。

### ISSUE THREAD

**Issue by yamazaki-seiya** [Kazuya-KT/FavPicker#3]
https://github.com/Kazuya-KT/FavPicker/blob/548a6a093996630066071fdc30e6cce184b422e3/FavPicker/myapp/favpicker/getimage.py#L85-L98

↓でいけます。
https://qiita.com/Uejun/items/5163ccadd5bdb4417f30

**Comment by Kazuya-KT** [comment]
Thanks.
Boto3参考に調べていけました。
https://stackoverflow.com/questions/14346065/upload-image-available-at-public-url-to-s3-using-boto/42493144#42493144
